language: java
jdk: oraclejdk8
dist: trusty
sudo: required

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false

install:
  - ./gradlew generateGrammar
  
script: ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: Build and Test
      env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.5
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.5
    - stage: Deploy new Release
      script: skip
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.5
      deploy:
        - provider: script
          script: ./gradlew publishPlugin
          skip_cleanup: true
          on:
            tags: true
            repo: DmytroTroynikov/aemtools
        - provider: releases
          api_key: "generate yours: https://docs.travis-ci.com/user/deployment/releases/"
          file_glob: true
          file: "build/distributions/*"
          skip_cleanup: true
          on:
            tags: true
            repo: DmytroTroynikov/aemtools
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
