branches:
  only:
    - develop

pull_requests:
  disable: true

build:
  verbosity: detailed

build_script:
  - gradlew.bat buildPlugin --info

test_script:
  - gradlew.bat koverHtmlReport verifyPlugin --info

environment:
  JAVA_HOME: C:\Program Files\Java\jdk21
  JAVA_OPTS: "-Xms256m -Xmx3072m -Djdk.tls.client.protocols=TLSv1.2"
  GRADLE_OPTS: "-Xms256m -Xmx3072m -Djdk.tls.client.protocols=TLSv1.2"
  matrix:
    - ORG_GRADLE_PROJECT_ideaVersion: 2024.3
