package com.aemtools.sync.settings.gui

/**
 * @author Dmytro Liakhov
 */


import com.intellij.uiDesigner.core.GridConstraints
import com.intellij.uiDesigner.core.GridLayoutManager
import com.intellij.uiDesigner.core.Spacer
import java.awt.Insets
import javax.swing.JCheckBox
import javax.swing.JPanel


/**
 * @author Dmytro Liakhov
 */
class AEMToolsConfigurationGUI {
  private var rootPanel: JCheckBox? = null
  var labelEnableSync: JPanel? = null
    private set

  init {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    `$$$setupUI$$$`()
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private fun `$$$setupUI$$$`() {
    val panel1 = JPanel()
    panel1.layout = GridLayoutManager(2, 1, Insets(0, 0, 0, 0), -1, -1)
    labelEnableSync = JPanel()
    labelEnableSync!!.layout = GridLayoutManager(1, 2, Insets(0, 0, 0, 0), -1, -1)
    labelEnableSync!!.toolTipText = "Enable Sync Files"
    panel1.add(labelEnableSync!!, GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK or GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK or GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false))
    rootPanel = JCheckBox()
    rootPanel!!.text = "Enable"
    labelEnableSync!!.add(rootPanel!!, GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK or GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false))
    val spacer1 = Spacer()
    labelEnableSync!!.add(spacer1, GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false))
    val spacer2 = Spacer()
    panel1.add(spacer2, GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false))
  }

}
